
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ""
  region: ""
nodeGroups:
  

# managedNodeGroups:
#   - name: nodegroup-1
#     instanceType: t3a.small
#     availabilityZones: ["us-east-2b"]
#     minSize: 1
#     maxSize: 2
#     desiredCapacity: 2
#     volumeSize: 10
#     volumeType: gp2
#     tags:
#       env: dev
#       node-class: tiny
#   - name: nodegroup-2
#     instanceType: t3a.large
#     availabilityZones: ["us-east-2b"]
#     minSize: 1
#     maxSize: 1
#     desiredCapacity: 1
#     volumeSize: 10
#     volumeType: gp2
#     tags:
#       env: dev
#       node-class: large
#     # ssh:
#     #   publicKeyName: my-ssh-key
