apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: ingress-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "tools."
      # tls:
      #   httpsRedirect: true
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: ingress-letsencrypt # must be the same as secret
      hosts:
        - "tools."
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "grafana-ingress"
spec:
  hosts:
    - "tools."
  gateways:
    - ingress-gateway
  exportTo:
    - "*"
  http:
    - match:
        - uri:
            prefix: "/grafana/"
        - uri:
            exact: "/grafana"
      rewrite:
        uri: "/grafana/"
      route:
        - destination:
            port:
              number: 80
            host: grafana.tools.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "kiali-ingress"
spec:
  hosts:
    - "tools."
  gateways:
    - ingress-gateway
  exportTo:
    - "*"
  http:
    - match:
        - uri:
            prefix: "/kiali/"
        - uri:
            exact: "/kiali"
      rewrite:
        uri: "/kiali/"
      route:
        - destination:
            port:
              number: 20001
            host: kiali.tools.svc.cluster.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "jaeger-ingress"
spec:
  hosts:
    - "tools."
  gateways:
    - ingress-gateway
  exportTo:
    - "*"
  http:
    - match:
        - uri:
            prefix: "/jaeger/"
        - uri:
            exact: "/jaeger"
      rewrite:
        uri: "/"
      route:
        - destination:
            port:
              number: 16686
            host: tracing-jaeger-query.tools.svc.cluster.local
---

