name: "Build and deploy image"

on:
  [push]
  # push:
  #   tags:
  #     - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # pull_request:
  #   tags:
  #     - "v*"

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and Push Img
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github container repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        id: build-push
        with:
          context: .
          file: ./Dockerfile
          #   platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: ghcr.io/argonautdev/sampleimage:latest
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/argonautdev/ci:latest
    steps:
      - name: Deploy art
        run: art app deploy -k $AWS_ID -v $AWS_SECRET -f .art/art.yaml -i nginx -t latest -p $CR_PAT
